name: CI/CD Pipeline for Docker
'on':
  schedule:
  - cron: ${{ secrets.DAILY_CRON }}
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - run: ./bin/build
      name: Build Docker image
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db:
        - postgres
        - mysql
        - mssql
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - run: ./test/test ${{ matrix.db }}
      name: Test with ${{ matrix.db }}
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scan_type:
        - fixable
        - all
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - run: TAG=$(cat VERSION)
      name: Scan Docker image for ${{ matrix.scan_type }} issues
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - run: ./bin/publish
      name: Publish Docker image
